dataset: 'cifar10'
data_dir: './../data'


client_num_in_total: 10
client_num_per_round: 5
comm_round: 100
global_epochs_per_round: 5
num_classes: 10
model_input_channels: 3

record_tool: 'wandb'  # using wandb or tensorboard
wandb_record: True

#     tuning these 4 parametes for VAE 

VAE_re: 5.0
VAE_ce: 2.0
VAE_kl: 0.005
VAE_x_ce: 0.4


#    strength of noise
VAE_std1: 0.2
VAE_std2: 0.25
noise_type: 'Gaussian'  # Gaussian or Laplace
